---
name: "Scality Upload SBOM Action"
description: "Upload an SBOM (Software Bill Of Materials) to Dependency Track."
author: "Scality"
branding:
  color: blue
  icon: shield
inputs:
  url:
    description: "Dependency Track server URL"
    required: false

  api-key:
    description: "Dependency Track API key"
    required: false

  project-sbom:
    description: "Path to the SBOM file to upload"
    required: false

  project-sbom-list:
    description: "Path to a text file containing a list of SBOM files to upload (one per line)"
    required: false

  project-sbom-dir:
    description: "Directory containing SBOM files to upload as child projects"
    required: false

  project-name:
    description: "Project name in Dependency Track"
    required: false
    default: ""

  parent-project-name:
    description: "Parent project name in Dependency Track (if applicable)"
    required: false
    default: ""

  project-version:
    description: "Project version in Dependency Track"
    required: false
    default: ""

  parent-project-version:
    description: "Parent project version in Dependency Track (if applicable)"
    required: false
    default: ""

  project-description:
    description: "Project description in Dependency Track"
    required: false
    default: ""

  project-uuid:
    description: "Project UUID in Dependency Track (if known)"
    required: false
    default: ""

  project-prefix:
    description: "Prefix to add to project name"
    required: false
    default: ""

  project-suffix:
    description: "Suffix to add to project name"
    required: false
    default: ""

  project-classifier:
    description: "Project classifier in Dependency Track"
    required: false
    default: "APPLICATION"

  parent-project-classifier:
    description: "Parent project classifier in Dependency Track (if applicable)"
    required: false
    default: "APPLICATION"

  project-collection-logic:
    description: "Project collection logic in Dependency Track"
    required: false
    default: "NONE"

  parent-project-collection-logic:
    description: "Parent project collection logic in Dependency Track (if applicable)"
    required: false
    default: "NONE"

  project-tags:
    description: "Comma-separated list of tags to apply to the project"
    required: false
    default: ""

  is-latest:
    description: "Set the 'latest' flag on the uploaded project version"
    required: false
    default: "false"

  auto-detect-latest:
    description: "Automatically detect and set the latest version flag based on semantic versioning"
    required: false
    default: "true"

  api-timeout:
    description: "API request timeout in seconds (increase for slow networks or large projects)"
    required: false
    default: "300"

  dry-run:
    description: "Enable dry run mode (no actual uploads, just validation and logging)"
    required: false
    default: "false"

  # Hierarchy Generation Inputs
  generate-hierarchy:
    description: "Generate hierarchical configuration from nested SBOM directory structure"
    required: false
    default: "false"

  hierarchy-input-dir:
    description: "Input directory containing nested SBOM structure for hierarchy generation"
    required: false
    default: ""

  hierarchy-output-file:
    description: "Output file path for generated hierarchy configuration JSON"
    required: false
    default: ""

  hierarchy-upload:
    description: "Automatically upload the generated hierarchy to Dependency Track"
    required: false
    default: "false"

outputs:
  # Dependency Track Upload Outputs
  upload-summary:
    description: "JSON summary of uploaded projects and versions"

  projects-created:
    description: "Number of new projects created"

  projects-updated:
    description: "Number of existing projects updated"

  sboms-uploaded:
    description: "Number of SBOM files uploaded"

  latest-flags-updated:
    description: "Number of latest flags updated"
  
  latest-versions:
    description: "List of projects where latest flag was updated"
    
  upload-errors:
    description: "List of any upload errors encountered"

  # Hierarchy Generation Outputs
  hierarchy-config-file:
    description: "Path to the generated hierarchy configuration file"

  hierarchy-projects-count:
    description: "Total number of projects in the generated hierarchy"

  hierarchy-top-level-projects:
    description: "Number of top-level projects in the hierarchy"

runs:
  using: "composite"
  steps:
    - name: Install Python 3
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: "pip"

    - name: Install python deps
      shell: bash
      run: |
        if [ -f "${{ github.action_path }}/requirements.txt" ]; then
          pip install -r "${{ github.action_path }}/requirements.txt"
        else
          echo "No requirements.txt found; skipping Python dependencies installation."
        fi

    - name: Install dependencies
      shell: bash
      run: |
          export DEBIAN_FRONTEND=noninteractive && \
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends -y \
          file \
          jq \
          p7zip-full \
          python3-setuptools

    - name: Run the upload
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_PROJECT_SBOM: ${{ inputs.project-sbom }}
        INPUT_PROJECT_SBOM_LIST: ${{ inputs.project-sbom-list }}
        INPUT_PROJECT_SBOM_DIR: ${{ inputs.project-sbom-dir }}
        INPUT_PROJECT_NAME: ${{ inputs.project-name }}
        INPUT_PARENT_PROJECT_NAME: ${{ inputs.parent-project-name }}
        INPUT_PROJECT_UUID: ${{ inputs.project-uuid }}
        INPUT_PROJECT_VERSION: ${{ inputs.project-version }}
        INPUT_PARENT_PROJECT_VERSION: ${{ inputs.parent-project-version }}
        INPUT_PROJECT_DESCRIPTION: ${{ inputs.project-description }}
        INPUT_PROJECT_PREFIX: ${{ inputs.project-prefix }}
        INPUT_PROJECT_SUFFIX: ${{ inputs.project-suffix }}
        INPUT_PROJECT_CLASSIFIER: ${{ inputs.project-classifier }}
        INPUT_PARENT_PROJECT_CLASSIFIER: ${{ inputs.parent-project-classifier }}
        INPUT_PROJECT_COLLECTION_LOGIC: ${{ inputs.project-collection-logic }}
        INPUT_PARENT_PROJECT_COLLECTION_LOGIC: ${{ inputs.parent-project-collection-logic }}
        INPUT_PROJECT_TAGS: ${{ inputs.project-tags }}
        INPUT_IS_LATEST: ${{ inputs.is-latest }}
        INPUT_AUTO_DETECT_LATEST: ${{ inputs.auto-detect-latest }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_GENERATE_HIERARCHY: ${{ inputs.generate-hierarchy }}
        INPUT_HIERARCHY_INPUT_DIR: ${{ inputs.hierarchy-input-dir }}
        INPUT_HIERARCHY_OUTPUT_FILE: ${{ inputs.hierarchy-output-file }}
        INPUT_HIERARCHY_UPLOAD: ${{ inputs.hierarchy-upload }}

      run: |
        if [ "${{ inputs.generate-hierarchy }}" = "true" ]; then
          python3 ${{ github.action_path }}/src/main.py generate-hierarchy-action
        else
          python3 ${{ github.action_path }}/src/main.py upload
        fi
